source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!
target 'testdemo' do

#tools
#pod 'Alamofire'
#pod 'Kingfisher'
#pod 'HandyJSON', :git => 'https://github.com/Baymax0/HandyJSON.git'
#pod 'MJRefresh'
#pod 'SwiftyUserDefaults'
#pod 'IQKeyboardManagerSwift'
#pod 'SQLite.swift'
#
#pod 'Hero'
#pod 'NVActivityIndicatorView'
#pod 'CLImagePickerTool'
#
#pod 'AttributedString'

end
